package jonas.tool.httpRequestCreator.Constants;

public class HttpHeadersList {
	public static final String[] STANDARD_REQUEST_HEADER_NAMES = {
		"Accept",
		"Accept-Charset",
		"Accept-Encoding",
		"Accept-Language",
		"Accept-Datetime",
		"Authorization",
		"Cache-Control",
		"Connection",
		"Cookie",
		"Content-Length",
		"Content-MD5",
		"Content-Type",
		"Date",
		"Expect",
		"From",
		"Host",
		"If-Match",
		"If-None-Match",
		"If-Range",
		"If-Unmodified-Since",
		"Max-Forwards",
		"Origin",
		"Pragma",
		"Proxy-Authorization",
		"Referer",
		"TE",
		"User-Agent",
		"Upgrade",
		"Via",
		"Warning",
		
		"X-Requested-With",
		"DNT",
		"X-Forwarded-For",
		"X-Forwarded-Host",
		"X-Forwarded-Proto",
		"Front-End-Https",
		"X-Http-Method-Override",
		"X-Wap-Profile",
		"Proxy-Connection",
		"X-Csrf-Token",
		"X-CSRFToken",
		"X-XSRF-TOKEN",
		
		"Username",
		"Password"
	};
	
	public static final String[] STANDARD_REQUEST_HEADER_DESCRIPTIONS = {
		"Accept",
		"Accept-Charset",
		"Accept-Encoding",
		"Accept-Language",
		"Accept-Datetime",
		"Authorization",
		"Cache-Control",
		"Connection",
		"Cookie",
		"Content-Length",
		"Content-MD5",
		"Content-Type",
		"Date",
		"Expect",
		"From",
		"Host",
		"If-Match",
		"If-None-Match",
		"If-Range",
		"If-Unmodified-Since",
		"Max-Forwards",
		"Origin",
		"Pragma",
		"Proxy-Authorization",
		"Referer",
		"TE",
		"User-Agent",
		"Upgrade",
		"Via",
		"Warning",

		"X-Requested-With",
		"DNT",
		"X-Forwarded-For",
		"X-Forwarded-Host",
		"X-Forwarded-Proto",
		"Front-End-Https",
		"X-Http-Method-Override",
		"X-Wap-Profile",
		"Proxy-Connection",
		"X-Csrf-Token",
		"X-CSRFToken",
		"X-XSRF-TOKEN",

		"Username",
		"Password"
	};
}
